spring.application.name=http3

server.port=${SERVER_PORT:8444}
server.http2.enabled=true

logging.level.org.springframework=INFO
logging.level.org.eclipse.jetty=DEBUG
logging.level.org.eclipse.jetty.http3=DEBUG
logging.level.org.eclipse.jetty.quic=DEBUG

server.servlet.session.timeout=900
server.jetty.connection-idle-timeout=900000