spring.application.name=http3

server.port=${SERVER_PORT:8443}
server.http2.enabled=true


server.ssl.bundle=service
spring.ssl.bundle.jks.service.key.alias=service
spring.ssl.bundle.jks.service.keystore.location=classpath:service-keystore.p12
spring.ssl.bundle.jks.service.keystore.password=secret
spring.ssl.bundle.jks.service.keystore.type=PKCS12
spring.ssl.bundle.pem.client.truststore.certificate=classpath:certificate.pem

logging.level.org.springframework=INFO


server.servlet.session.timeout=900
server.jetty.connection-idle-timeout=900000