@startuml
title 0-RTT in QUIC Protocol

participant Client
participant Server

group 0-RTT
Client -> Server: Initial Packet (ClientHello) \n*KeyShare
Server -> Client: Finished  (ServerHello)\n*KeyShare\n*certificate\n*Signature]
Client -> Server: Finished
end
group 1-RTT
Client -> Server: 1-RTT Data
Server -> Client: 1-RTT Data
end

@enduml