#!/bin/bash

# Maven Conversion Script for HTTP/3 Client Test Project
# Converts from Gradle to Maven build system

echo "🔄 Converting HTTP/3 Client Test Project from Gradle to Maven"
echo "=============================================================="
echo ""

PROJECT_DIR="/home/grxybek/tata/http3-client-test"
cd "$PROJECT_DIR"

echo "📋 Conversion Steps:"
echo "1. Created pom.xml with all Gradle dependencies"
echo "2. Updated .gitignore for Maven patterns"
echo "3. Gradle files will be moved to sandbox/"
echo ""

echo "✅ Maven Configuration Created:"
echo "==============================="
echo "• pom.xml - Main Maven configuration"
echo "• Java 23 with preview features enabled"
echo "• Spring Boot 3.3.5"
echo "• Jetty HTTP/3 support (12.0.1)"
echo "• All original Gradle dependencies included"
echo ""

echo "📦 Key Dependencies in Maven:"
echo "=============================="
echo "• Spring Boot Starter Web (without Tomcat)"
echo "• Spring Boot Starter Jetty"
echo "• Jetty HTTP/3 Server (12.0.1)"
echo "• Jetty HTTP/2 Server (12.0.1)"
echo "• Reactor Netty HTTP"
echo "• Netty HTTP/3 Incubator (0.0.28.Final)"
echo "• KWIK Flupke HTTP/3 Client (0.5.3)"
echo "• Gson (2.11.0)"
echo ""

echo "🔧 Maven Commands:"
echo "=================="
echo "• Build project: mvn clean compile"
echo "• Run tests: mvn test"
echo "• Package: mvn package"
echo "• Run Spring Boot app: mvn spring-boot:run"
echo "• Install dependencies: mvn dependency:resolve"
echo ""

echo "📁 Project Structure (Maven Standard):"
echo "======================================"
echo "src/"
echo "├── main/"
echo "│   ├── java/          # Main Java sources"
echo "│   ├── java26/        # Java 26 specific sources (profile)"
echo "│   └── resources/     # Application resources"
echo "└── test/"
echo "    ├── java/          # Test sources"
echo "    └── resources/     # Test resources"
echo ""

echo "🎯 Special Features:"
echo "==================="
echo "• Java 23 with --enable-preview"
echo "• Java 26 profile (mvn -Pjava26)"
echo "• Development profile with SSL key logging"
echo "• Spring Boot integration"
echo "• HTTP/3 and QUIC support"
echo ""

echo "🔬 Development Profile:"
echo "======================"
echo "Run with development features:"
echo "mvn spring-boot:run -Pdevelopment"
echo ""
echo "This enables:"
echo "• SSL key logging to /tmp/http3_debug.key_log"
echo "• Enhanced debugging"
echo "• Development Spring profile"
echo ""

echo "🚀 Quick Start:"
echo "==============="
echo "1. Install Maven dependencies:"
echo "   mvn dependency:resolve"
echo ""
echo "2. Compile the project:"
echo "   mvn clean compile"
echo ""
echo "3. Run tests:"
echo "   mvn test"
echo ""
echo "4. Run the application:"
echo "   mvn spring-boot:run"
echo ""

echo "📊 Java 26 Profile Usage:"
echo "========================="
echo "For Java 26 specific features:"
echo "mvn clean compile -Pjava26"
echo "mvn spring-boot:run -Pjava26"
echo ""

echo "🔍 Dependency Analysis:"
echo "======================"
echo "• Check dependencies: mvn dependency:tree"
echo "• Update dependencies: mvn versions:display-dependency-updates"
echo "• Effective POM: mvn help:effective-pom"
echo ""

echo "💡 Migration Notes:"
echo "=================="
echo "• All Gradle dependencies have been mapped to Maven"
echo "• Java 23 preview features are enabled"
echo "• Spring Boot plugin configured for HTTP/3"
echo "• Test configuration includes --enable-preview"
echo "• Profiles available for different Java versions"
echo ""

echo "✅ Conversion Complete!"
echo ""
echo "Next steps:"
echo "1. Test the Maven build: mvn clean compile"
echo "2. Run the application: mvn spring-boot:run"
echo "3. Move Gradle files to sandbox if everything works"
echo ""

# Verify Maven is available
if command -v mvn >/dev/null 2>&1; then
    echo "🔧 Maven is available. You can now use Maven commands."
    mvn --version
else
    echo "⚠️  Maven not found. Please install Maven to use the new build system."
    echo "   Ubuntu/Debian: sudo apt install maven"
    echo "   macOS: brew install maven"
fi